### PR TITLE
Foundations/code refactoring

### PR DESCRIPTION
**Pull request by maheshkkumar**
- Refactored Bitcoin APIs
- Refactored Ethereum APIs
- Created `utils` folder for common utility functions used by the APIs

### CODE REVIEW

**Comment by cakcora** [comment]
this is asking me to resolve conflicts by command line. It seems that two files are conflicted, and some changes will be lost. @maheshkkumar, do you know why has this happened?

**Comment by maheshkkumar** [comment]
@cakcora: I will take a look at the merge conflict and will resolve it soon.

**Comment by maheshkkumar** [comment]
@cakcora: I have resolved the conflicts.

**Comment by cakcora** [comment]
Thanks a lot Mahesh

**Pull request merged**
